# Makefile for assignment 5
# Author: Jay Hennen
# Not very useful except to elimiate typing

CFLAGS = -Wall -g -o

SUPPORT_FILES = Event.cpp State.cpp
SUPPORT_CPP = Event.cpp State.cpp

micro: Microwave.cpp $(SUPPORT_FILES)
	g++ $(CFLAGS) micro Microwave.cpp $(SUPPORT_CPP)
